import '../../../../../require.js';
import '../../../../../exports.js';
import '../../../../base/common/codicons.js';
import '../../../../nls.js';
import '../../../../platform/theme/common/iconRegistry.js';
define(de[1903], he([1, 0, 14, 4, 79]), function (ce /*require*/,
 e /*exports*/,
 t /*codicons*/,
 i /*nls*/,
 w /*iconRegistry*/) {
			"use strict";
			Object.defineProperty(e, "__esModule", { value: !0 }),
				(e.$grc = e.$frc = void 0),
				(e.$frc = (0, w.$$O)(
					"settings-view-bar-icon",
					t.$ak.settingsGear,
					(0, i.localize)(12964, null),
				)),
				(e.$grc = [
					e.$frc,
					t.$ak.vm,
					t.$ak.server,
					t.$ak.recordKeys,
					t.$ak.deviceMobile,
					t.$ak.watch,
					t.$ak.vr,
					t.$ak.piano,
					t.$ak.ruby,
					t.$ak.code,
					t.$ak.coffee,
					t.$ak.snake,
					t.$ak.window,
					t.$ak.library,
					t.$ak.extensions,
					t.$ak.terminal,
					t.$ak.beaker,
					t.$ak.package,
					t.$ak.cloud,
					t.$ak.book,
					t.$ak.globe,
					t.$ak.database,
					t.$ak.notebook,
					t.$ak.robot,
					t.$ak.game,
					t.$ak.chip,
					t.$ak.music,
					t.$ak.gift,
					t.$ak.send,
					t.$ak.briefcase,
					t.$ak.megaphone,
					t.$ak.comment,
					t.$ak.telescope,
					t.$ak.creditCard,
					t.$ak.map,
					t.$ak.deviceCameraVideo,
					t.$ak.unmute,
					t.$ak.law,
					t.$ak.graphLine,
					t.$ak.heart,
					t.$ak.home,
					t.$ak.inbox,
					t.$ak.mortarBoard,
					t.$ak.rocket,
					t.$ak.magnet,
					t.$ak.lock,
					t.$ak.milestone,
					t.$ak.tag,
					t.$ak.pulse,
					t.$ak.radioTower,
					t.$ak.smiley,
					t.$ak.zap,
					t.$ak.squirrel,
					t.$ak.symbolColor,
					t.$ak.mail,
					t.$ak.key,
					t.$ak.pieChart,
					t.$ak.organization,
					t.$ak.preview,
					t.$ak.wand,
					t.$ak.starEmpty,
					t.$ak.lightbulb,
					t.$ak.symbolRuler,
					t.$ak.dashboard,
					t.$ak.calendar,
					t.$ak.shield,
					t.$ak.flame,
					t.$ak.compass,
					t.$ak.paintcan,
					t.$ak.archive,
					t.$ak.mic,
					t.$ak.jersey,
				]);
		}),
		