define(de[554], he([1, 0, 4, 8]), function (ce, e, t, i) {
			"use strict";
			Object.defineProperty(e, "__esModule", { value: !0 }),
				(e.$qVb =
					e.$pVb =
					e.$oVb =
					e.$nVb =
					e.$mVb =
					e.$lVb =
					e.$kVb =
					e.$jVb =
					e.$iVb =
					e.$hVb =
					e.$gVb =
					e.$fVb =
					e.$eVb =
					e.$dVb =
					e.$cVb =
					e.$bVb =
					e.$aVb =
					e.$_Ub =
					e.$$Ub =
					e.$0Ub =
					e.$9Ub =
					e.$8Ub =
					e.$7Ub =
					e.$6Ub =
					e.$5Ub =
					e.$4Ub =
					e.$3Ub =
					e.$2Ub =
					e.$1Ub =
					e.$ZUb =
					e.$YUb =
					e.$XUb =
					e.$WUb =
					e.$VUb =
						void 0),
				(t = mt(t)),
				(e.$VUb = "revealInExplorer"),
				(e.$WUb = "workbench.action.files.revert"),
				(e.$XUb = "explorer.openToSide"),
				(e.$YUb = "explorer.openWith"),
				(e.$ZUb = "selectForCompare"),
				(e.$1Ub = "compareSelected"),
				(e.$2Ub = "compareFiles"),
				(e.$3Ub = "workbench.files.action.compareWithSaved"),
				(e.$4Ub = "copyFilePath"),
				(e.$5Ub = "copyRelativeFilePath"),
				(e.$6Ub = "workbench.action.files.saveAs"),
				(e.$7Ub = t.localize2(6835, "Save As...")),
				(e.$8Ub = "workbench.action.files.save"),
				(e.$9Ub = t.localize2(6836, "Save")),
				(e.$0Ub = "workbench.action.files.saveWithoutFormatting"),
				(e.$$Ub = t.localize2(6837, "Save without Formatting")),
				(e.$_Ub = "saveAll"),
				(e.$aVb = t.localize2(6838, "Save All")),
				(e.$bVb = "workbench.files.action.saveAllInGroup"),
				(e.$cVb = "workbench.action.files.saveFiles"),
				(e.$dVb = new i.$5j("groupFocusedInOpenEditors", !1)),
				(e.$eVb = new i.$5j("dirtyEditorFocusedInOpenEditors", !1)),
				(e.$fVb = new i.$5j("readonlyEditorFocusedInOpenEditors", !1)),
				(e.$gVb = new i.$5j("openEditorsSelectedFileOrUntitled", !0)),
				(e.$hVb = new i.$5j("resourceSelectedForCompare", !1)),
				(e.$iVb = "removeRootFolder"),
				(e.$jVb = t.localize(6834, null)),
				(e.$kVb = "previousCompressedFolder"),
				(e.$lVb = "nextCompressedFolder"),
				(e.$mVb = "firstCompressedFolder"),
				(e.$nVb = "lastCompressedFolder"),
				(e.$oVb = "workbench.action.files.newUntitledFile"),
				(e.$pVb = t.localize2(6839, "New Untitled Text File")),
				(e.$qVb = "workbench.action.files.newFile");
		}),
		