import '../../../require.js';
import '../../../exports.js';
define(de[27], he([1, 0]), function (ce /*require*/,
 e /*exports*/) {
			"use strict";
			Object.defineProperty(e, "__esModule", { value: !0 }),
				(e.$qs =
					e.$ps =
					e.KeyMod =
					e.KeyCodeUtils =
					e.$ns =
					e.$ms =
					e.$ls =
					e.$ks =
					e.$js =
					e.ScanCode =
					e.KeyCode =
						void 0),
				(e.$os = c);
			var t;
			(function (n) {
				(n[(n.DependsOnKbLayout = -1)] = "DependsOnKbLayout"),
					(n[(n.Unknown = 0)] = "Unknown"),
					(n[(n.Backspace = 1)] = "Backspace"),
					(n[(n.Tab = 2)] = "Tab"),
					(n[(n.Enter = 3)] = "Enter"),
					(n[(n.Shift = 4)] = "Shift"),
					(n[(n.Ctrl = 5)] = "Ctrl"),
					(n[(n.Alt = 6)] = "Alt"),
					(n[(n.PauseBreak = 7)] = "PauseBreak"),
					(n[(n.CapsLock = 8)] = "CapsLock"),
					(n[(n.Escape = 9)] = "Escape"),
					(n[(n.Space = 10)] = "Space"),
					(n[(n.PageUp = 11)] = "PageUp"),
					(n[(n.PageDown = 12)] = "PageDown"),
					(n[(n.End = 13)] = "End"),
					(n[(n.Home = 14)] = "Home"),
					(n[(n.LeftArrow = 15)] = "LeftArrow"),
					(n[(n.UpArrow = 16)] = "UpArrow"),
					(n[(n.RightArrow = 17)] = "RightArrow"),
					(n[(n.DownArrow = 18)] = "DownArrow"),
					(n[(n.Insert = 19)] = "Insert"),
					(n[(n.Delete = 20)] = "Delete"),
					(n[(n.Digit0 = 21)] = "Digit0"),
					(n[(n.Digit1 = 22)] = "Digit1"),
					(n[(n.Digit2 = 23)] = "Digit2"),
					(n[(n.Digit3 = 24)] = "Digit3"),
					(n[(n.Digit4 = 25)] = "Digit4"),
					(n[(n.Digit5 = 26)] = "Digit5"),
					(n[(n.Digit6 = 27)] = "Digit6"),
					(n[(n.Digit7 = 28)] = "Digit7"),
					(n[(n.Digit8 = 29)] = "Digit8"),
					(n[(n.Digit9 = 30)] = "Digit9"),
					(n[(n.KeyA = 31)] = "KeyA"),
					(n[(n.KeyB = 32)] = "KeyB"),
					(n[(n.KeyC = 33)] = "KeyC"),
					(n[(n.KeyD = 34)] = "KeyD"),
					(n[(n.KeyE = 35)] = "KeyE"),
					(n[(n.KeyF = 36)] = "KeyF"),
					(n[(n.KeyG = 37)] = "KeyG"),
					(n[(n.KeyH = 38)] = "KeyH"),
					(n[(n.KeyI = 39)] = "KeyI"),
					(n[(n.KeyJ = 40)] = "KeyJ"),
					(n[(n.KeyK = 41)] = "KeyK"),
					(n[(n.KeyL = 42)] = "KeyL"),
					(n[(n.KeyM = 43)] = "KeyM"),
					(n[(n.KeyN = 44)] = "KeyN"),
					(n[(n.KeyO = 45)] = "KeyO"),
					(n[(n.KeyP = 46)] = "KeyP"),
					(n[(n.KeyQ = 47)] = "KeyQ"),
					(n[(n.KeyR = 48)] = "KeyR"),
					(n[(n.KeyS = 49)] = "KeyS"),
					(n[(n.KeyT = 50)] = "KeyT"),
					(n[(n.KeyU = 51)] = "KeyU"),
					(n[(n.KeyV = 52)] = "KeyV"),
					(n[(n.KeyW = 53)] = "KeyW"),
					(n[(n.KeyX = 54)] = "KeyX"),
					(n[(n.KeyY = 55)] = "KeyY"),
					(n[(n.KeyZ = 56)] = "KeyZ"),
					(n[(n.Meta = 57)] = "Meta"),
					(n[(n.ContextMenu = 58)] = "ContextMenu"),
					(n[(n.F1 = 59)] = "F1"),
					(n[(n.F2 = 60)] = "F2"),
					(n[(n.F3 = 61)] = "F3"),
					(n[(n.F4 = 62)] = "F4"),
					(n[(n.F5 = 63)] = "F5"),
					(n[(n.F6 = 64)] = "F6"),
					(n[(n.F7 = 65)] = "F7"),
					(n[(n.F8 = 66)] = "F8"),
					(n[(n.F9 = 67)] = "F9"),
					(n[(n.F10 = 68)] = "F10"),
					(n[(n.F11 = 69)] = "F11"),
					(n[(n.F12 = 70)] = "F12"),
					(n[(n.F13 = 71)] = "F13"),
					(n[(n.F14 = 72)] = "F14"),
					(n[(n.F15 = 73)] = "F15"),
					(n[(n.F16 = 74)] = "F16"),
					(n[(n.F17 = 75)] = "F17"),
					(n[(n.F18 = 76)] = "F18"),
					(n[(n.F19 = 77)] = "F19"),
					(n[(n.F20 = 78)] = "F20"),
					(n[(n.F21 = 79)] = "F21"),
					(n[(n.F22 = 80)] = "F22"),
					(n[(n.F23 = 81)] = "F23"),
					(n[(n.F24 = 82)] = "F24"),
					(n[(n.NumLock = 83)] = "NumLock"),
					(n[(n.ScrollLock = 84)] = "ScrollLock"),
					(n[(n.Semicolon = 85)] = "Semicolon"),
					(n[(n.Equal = 86)] = "Equal"),
					(n[(n.Comma = 87)] = "Comma"),
					(n[(n.Minus = 88)] = "Minus"),
					(n[(n.Period = 89)] = "Period"),
					(n[(n.Slash = 90)] = "Slash"),
					(n[(n.Backquote = 91)] = "Backquote"),
					(n[(n.BracketLeft = 92)] = "BracketLeft"),
					(n[(n.Backslash = 93)] = "Backslash"),
					(n[(n.BracketRight = 94)] = "BracketRight"),
					(n[(n.Quote = 95)] = "Quote"),
					(n[(n.OEM_8 = 96)] = "OEM_8"),
					(n[(n.IntlBackslash = 97)] = "IntlBackslash"),
					(n[(n.Numpad0 = 98)] = "Numpad0"),
					(n[(n.Numpad1 = 99)] = "Numpad1"),
					(n[(n.Numpad2 = 100)] = "Numpad2"),
					(n[(n.Numpad3 = 101)] = "Numpad3"),
					(n[(n.Numpad4 = 102)] = "Numpad4"),
					(n[(n.Numpad5 = 103)] = "Numpad5"),
					(n[(n.Numpad6 = 104)] = "Numpad6"),
					(n[(n.Numpad7 = 105)] = "Numpad7"),
					(n[(n.Numpad8 = 106)] = "Numpad8"),
					(n[(n.Numpad9 = 107)] = "Numpad9"),
					(n[(n.NumpadMultiply = 108)] = "NumpadMultiply"),
					(n[(n.NumpadAdd = 109)] = "NumpadAdd"),
					(n[(n.NUMPAD_SEPARATOR = 110)] = "NUMPAD_SEPARATOR"),
					(n[(n.NumpadSubtract = 111)] = "NumpadSubtract"),
					(n[(n.NumpadDecimal = 112)] = "NumpadDecimal"),
					(n[(n.NumpadDivide = 113)] = "NumpadDivide"),
					(n[(n.KEY_IN_COMPOSITION = 114)] = "KEY_IN_COMPOSITION"),
					(n[(n.ABNT_C1 = 115)] = "ABNT_C1"),
					(n[(n.ABNT_C2 = 116)] = "ABNT_C2"),
					(n[(n.AudioVolumeMute = 117)] = "AudioVolumeMute"),
					(n[(n.AudioVolumeUp = 118)] = "AudioVolumeUp"),
					(n[(n.AudioVolumeDown = 119)] = "AudioVolumeDown"),
					(n[(n.BrowserSearch = 120)] = "BrowserSearch"),
					(n[(n.BrowserHome = 121)] = "BrowserHome"),
					(n[(n.BrowserBack = 122)] = "BrowserBack"),
					(n[(n.BrowserForward = 123)] = "BrowserForward"),
					(n[(n.MediaTrackNext = 124)] = "MediaTrackNext"),
					(n[(n.MediaTrackPrevious = 125)] = "MediaTrackPrevious"),
					(n[(n.MediaStop = 126)] = "MediaStop"),
					(n[(n.MediaPlayPause = 127)] = "MediaPlayPause"),
					(n[(n.LaunchMediaPlayer = 128)] = "LaunchMediaPlayer"),
					(n[(n.LaunchMail = 129)] = "LaunchMail"),
					(n[(n.LaunchApp2 = 130)] = "LaunchApp2"),
					(n[(n.Clear = 131)] = "Clear"),
					(n[(n.MAX_VALUE = 132)] = "MAX_VALUE");
			})(t || (e.KeyCode = t = {}));
			var i;
			(function (n) {
				(n[(n.DependsOnKbLayout = -1)] = "DependsOnKbLayout"),
					(n[(n.None = 0)] = "None"),
					(n[(n.Hyper = 1)] = "Hyper"),
					(n[(n.Super = 2)] = "Super"),
					(n[(n.Fn = 3)] = "Fn"),
					(n[(n.FnLock = 4)] = "FnLock"),
					(n[(n.Suspend = 5)] = "Suspend"),
					(n[(n.Resume = 6)] = "Resume"),
					(n[(n.Turbo = 7)] = "Turbo"),
					(n[(n.Sleep = 8)] = "Sleep"),
					(n[(n.WakeUp = 9)] = "WakeUp"),
					(n[(n.KeyA = 10)] = "KeyA"),
					(n[(n.KeyB = 11)] = "KeyB"),
					(n[(n.KeyC = 12)] = "KeyC"),
					(n[(n.KeyD = 13)] = "KeyD"),
					(n[(n.KeyE = 14)] = "KeyE"),
					(n[(n.KeyF = 15)] = "KeyF"),
					(n[(n.KeyG = 16)] = "KeyG"),
					(n[(n.KeyH = 17)] = "KeyH"),
					(n[(n.KeyI = 18)] = "KeyI"),
					(n[(n.KeyJ = 19)] = "KeyJ"),
					(n[(n.KeyK = 20)] = "KeyK"),
					(n[(n.KeyL = 21)] = "KeyL"),
					(n[(n.KeyM = 22)] = "KeyM"),
					(n[(n.KeyN = 23)] = "KeyN"),
					(n[(n.KeyO = 24)] = "KeyO"),
					(n[(n.KeyP = 25)] = "KeyP"),
					(n[(n.KeyQ = 26)] = "KeyQ"),
					(n[(n.KeyR = 27)] = "KeyR"),
					(n[(n.KeyS = 28)] = "KeyS"),
					(n[(n.KeyT = 29)] = "KeyT"),
					(n[(n.KeyU = 30)] = "KeyU"),
					(n[(n.KeyV = 31)] = "KeyV"),
					(n[(n.KeyW = 32)] = "KeyW"),
					(n[(n.KeyX = 33)] = "KeyX"),
					(n[(n.KeyY = 34)] = "KeyY"),
					(n[(n.KeyZ = 35)] = "KeyZ"),
					(n[(n.Digit1 = 36)] = "Digit1"),
					(n[(n.Digit2 = 37)] = "Digit2"),
					(n[(n.Digit3 = 38)] = "Digit3"),
					(n[(n.Digit4 = 39)] = "Digit4"),
					(n[(n.Digit5 = 40)] = "Digit5"),
					(n[(n.Digit6 = 41)] = "Digit6"),
					(n[(n.Digit7 = 42)] = "Digit7"),
					(n[(n.Digit8 = 43)] = "Digit8"),
					(n[(n.Digit9 = 44)] = "Digit9"),
					(n[(n.Digit0 = 45)] = "Digit0"),
					(n[(n.Enter = 46)] = "Enter"),
					(n[(n.Escape = 47)] = "Escape"),
					(n[(n.Backspace = 48)] = "Backspace"),
					(n[(n.Tab = 49)] = "Tab"),
					(n[(n.Space = 50)] = "Space"),
					(n[(n.Minus = 51)] = "Minus"),
					(n[(n.Equal = 52)] = "Equal"),
					(n[(n.BracketLeft = 53)] = "BracketLeft"),
					(n[(n.BracketRight = 54)] = "BracketRight"),
					(n[(n.Backslash = 55)] = "Backslash"),
					(n[(n.IntlHash = 56)] = "IntlHash"),
					(n[(n.Semicolon = 57)] = "Semicolon"),
					(n[(n.Quote = 58)] = "Quote"),
					(n[(n.Backquote = 59)] = "Backquote"),
					(n[(n.Comma = 60)] = "Comma"),
					(n[(n.Period = 61)] = "Period"),
					(n[(n.Slash = 62)] = "Slash"),
					(n[(n.CapsLock = 63)] = "CapsLock"),
					(n[(n.F1 = 64)] = "F1"),
					(n[(n.F2 = 65)] = "F2"),
					(n[(n.F3 = 66)] = "F3"),
					(n[(n.F4 = 67)] = "F4"),
					(n[(n.F5 = 68)] = "F5"),
					(n[(n.F6 = 69)] = "F6"),
					(n[(n.F7 = 70)] = "F7"),
					(n[(n.F8 = 71)] = "F8"),
					(n[(n.F9 = 72)] = "F9"),
					(n[(n.F10 = 73)] = "F10"),
					(n[(n.F11 = 74)] = "F11"),
					(n[(n.F12 = 75)] = "F12"),
					(n[(n.PrintScreen = 76)] = "PrintScreen"),
					(n[(n.ScrollLock = 77)] = "ScrollLock"),
					(n[(n.Pause = 78)] = "Pause"),
					(n[(n.Insert = 79)] = "Insert"),
					(n[(n.Home = 80)] = "Home"),
					(n[(n.PageUp = 81)] = "PageUp"),
					(n[(n.Delete = 82)] = "Delete"),
					(n[(n.End = 83)] = "End"),
					(n[(n.PageDown = 84)] = "PageDown"),
					(n[(n.ArrowRight = 85)] = "ArrowRight"),
					(n[(n.ArrowLeft = 86)] = "ArrowLeft"),
					(n[(n.ArrowDown = 87)] = "ArrowDown"),
					(n[(n.ArrowUp = 88)] = "ArrowUp"),
					(n[(n.NumLock = 89)] = "NumLock"),
					(n[(n.NumpadDivide = 90)] = "NumpadDivide"),
					(n[(n.NumpadMultiply = 91)] = "NumpadMultiply"),
					(n[(n.NumpadSubtract = 92)] = "NumpadSubtract"),
					(n[(n.NumpadAdd = 93)] = "NumpadAdd"),
					(n[(n.NumpadEnter = 94)] = "NumpadEnter"),
					(n[(n.Numpad1 = 95)] = "Numpad1"),
					(n[(n.Numpad2 = 96)] = "Numpad2"),
					(n[(n.Numpad3 = 97)] = "Numpad3"),
					(n[(n.Numpad4 = 98)] = "Numpad4"),
					(n[(n.Numpad5 = 99)] = "Numpad5"),
					(n[(n.Numpad6 = 100)] = "Numpad6"),
					(n[(n.Numpad7 = 101)] = "Numpad7"),
					(n[(n.Numpad8 = 102)] = "Numpad8"),
					(n[(n.Numpad9 = 103)] = "Numpad9"),
					(n[(n.Numpad0 = 104)] = "Numpad0"),
					(n[(n.NumpadDecimal = 105)] = "NumpadDecimal"),
					(n[(n.IntlBackslash = 106)] = "IntlBackslash"),
					(n[(n.ContextMenu = 107)] = "ContextMenu"),
					(n[(n.Power = 108)] = "Power"),
					(n[(n.NumpadEqual = 109)] = "NumpadEqual"),
					(n[(n.F13 = 110)] = "F13"),
					(n[(n.F14 = 111)] = "F14"),
					(n[(n.F15 = 112)] = "F15"),
					(n[(n.F16 = 113)] = "F16"),
					(n[(n.F17 = 114)] = "F17"),
					(n[(n.F18 = 115)] = "F18"),
					(n[(n.F19 = 116)] = "F19"),
					(n[(n.F20 = 117)] = "F20"),
					(n[(n.F21 = 118)] = "F21"),
					(n[(n.F22 = 119)] = "F22"),
					(n[(n.F23 = 120)] = "F23"),
					(n[(n.F24 = 121)] = "F24"),
					(n[(n.Open = 122)] = "Open"),
					(n[(n.Help = 123)] = "Help"),
					(n[(n.Select = 124)] = "Select"),
					(n[(n.Again = 125)] = "Again"),
					(n[(n.Undo = 126)] = "Undo"),
					(n[(n.Cut = 127)] = "Cut"),
					(n[(n.Copy = 128)] = "Copy"),
					(n[(n.Paste = 129)] = "Paste"),
					(n[(n.Find = 130)] = "Find"),
					(n[(n.AudioVolumeMute = 131)] = "AudioVolumeMute"),
					(n[(n.AudioVolumeUp = 132)] = "AudioVolumeUp"),
					(n[(n.AudioVolumeDown = 133)] = "AudioVolumeDown"),
					(n[(n.NumpadComma = 134)] = "NumpadComma"),
					(n[(n.IntlRo = 135)] = "IntlRo"),
					(n[(n.KanaMode = 136)] = "KanaMode"),
					(n[(n.IntlYen = 137)] = "IntlYen"),
					(n[(n.Convert = 138)] = "Convert"),
					(n[(n.NonConvert = 139)] = "NonConvert"),
					(n[(n.Lang1 = 140)] = "Lang1"),
					(n[(n.Lang2 = 141)] = "Lang2"),
					(n[(n.Lang3 = 142)] = "Lang3"),
					(n[(n.Lang4 = 143)] = "Lang4"),
					(n[(n.Lang5 = 144)] = "Lang5"),
					(n[(n.Abort = 145)] = "Abort"),
					(n[(n.Props = 146)] = "Props"),
					(n[(n.NumpadParenLeft = 147)] = "NumpadParenLeft"),
					(n[(n.NumpadParenRight = 148)] = "NumpadParenRight"),
					(n[(n.NumpadBackspace = 149)] = "NumpadBackspace"),
					(n[(n.NumpadMemoryStore = 150)] = "NumpadMemoryStore"),
					(n[(n.NumpadMemoryRecall = 151)] = "NumpadMemoryRecall"),
					(n[(n.NumpadMemoryClear = 152)] = "NumpadMemoryClear"),
					(n[(n.NumpadMemoryAdd = 153)] = "NumpadMemoryAdd"),
					(n[(n.NumpadMemorySubtract = 154)] = "NumpadMemorySubtract"),
					(n[(n.NumpadClear = 155)] = "NumpadClear"),
					(n[(n.NumpadClearEntry = 156)] = "NumpadClearEntry"),
					(n[(n.ControlLeft = 157)] = "ControlLeft"),
					(n[(n.ShiftLeft = 158)] = "ShiftLeft"),
					(n[(n.AltLeft = 159)] = "AltLeft"),
					(n[(n.MetaLeft = 160)] = "MetaLeft"),
					(n[(n.ControlRight = 161)] = "ControlRight"),
					(n[(n.ShiftRight = 162)] = "ShiftRight"),
					(n[(n.AltRight = 163)] = "AltRight"),
					(n[(n.MetaRight = 164)] = "MetaRight"),
					(n[(n.BrightnessUp = 165)] = "BrightnessUp"),
					(n[(n.BrightnessDown = 166)] = "BrightnessDown"),
					(n[(n.MediaPlay = 167)] = "MediaPlay"),
					(n[(n.MediaRecord = 168)] = "MediaRecord"),
					(n[(n.MediaFastForward = 169)] = "MediaFastForward"),
					(n[(n.MediaRewind = 170)] = "MediaRewind"),
					(n[(n.MediaTrackNext = 171)] = "MediaTrackNext"),
					(n[(n.MediaTrackPrevious = 172)] = "MediaTrackPrevious"),
					(n[(n.MediaStop = 173)] = "MediaStop"),
					(n[(n.Eject = 174)] = "Eject"),
					(n[(n.MediaPlayPause = 175)] = "MediaPlayPause"),
					(n[(n.MediaSelect = 176)] = "MediaSelect"),
					(n[(n.LaunchMail = 177)] = "LaunchMail"),
					(n[(n.LaunchApp2 = 178)] = "LaunchApp2"),
					(n[(n.LaunchApp1 = 179)] = "LaunchApp1"),
					(n[(n.SelectTask = 180)] = "SelectTask"),
					(n[(n.LaunchScreenSaver = 181)] = "LaunchScreenSaver"),
					(n[(n.BrowserSearch = 182)] = "BrowserSearch"),
					(n[(n.BrowserHome = 183)] = "BrowserHome"),
					(n[(n.BrowserBack = 184)] = "BrowserBack"),
					(n[(n.BrowserForward = 185)] = "BrowserForward"),
					(n[(n.BrowserStop = 186)] = "BrowserStop"),
					(n[(n.BrowserRefresh = 187)] = "BrowserRefresh"),
					(n[(n.BrowserFavorites = 188)] = "BrowserFavorites"),
					(n[(n.ZoomToggle = 189)] = "ZoomToggle"),
					(n[(n.MailReply = 190)] = "MailReply"),
					(n[(n.MailForward = 191)] = "MailForward"),
					(n[(n.MailSend = 192)] = "MailSend"),
					(n[(n.MAX_VALUE = 193)] = "MAX_VALUE");
			})(i || (e.ScanCode = i = {}));
			class w {
				constructor() {
					(this._keyCodeToStr = []), (this._strToKeyCode = Object.create(null));
				}
				define(g, p) {
					(this._keyCodeToStr[g] = p),
						(this._strToKeyCode[p.toLowerCase()] = g);
				}
				keyCodeToStr(g) {
					return this._keyCodeToStr[g];
				}
				strToKeyCode(g) {
					return this._strToKeyCode[g.toLowerCase()] || t.Unknown;
				}
			}
			const E = new w(),
				C = new w(),
				d = new w();
			(e.$js = new Array(230)), (e.$ks = {});
			const m = [],
				r = Object.create(null),
				u = Object.create(null);
			(e.$ls = {
				lowerCaseToEnum: (n) => u[n] || i.None,
				toEnum: (n) => r[n] || i.None,
				toString: (n) => m[n] || "None",
			}),
				(e.$ms = []),
				(e.$ns = []);
			for (let n = 0; n <= i.MAX_VALUE; n++) e.$ms[n] = t.DependsOnKbLayout;
			for (let n = 0; n <= t.MAX_VALUE; n++) e.$ns[n] = i.DependsOnKbLayout;
			(function () {
				const n = "",
					g = [
						[1, i.None, "None", t.Unknown, "unknown", 0, "VK_UNKNOWN", n, n],
						[1, i.Hyper, "Hyper", t.Unknown, n, 0, n, n, n],
						[1, i.Super, "Super", t.Unknown, n, 0, n, n, n],
						[1, i.Fn, "Fn", t.Unknown, n, 0, n, n, n],
						[1, i.FnLock, "FnLock", t.Unknown, n, 0, n, n, n],
						[1, i.Suspend, "Suspend", t.Unknown, n, 0, n, n, n],
						[1, i.Resume, "Resume", t.Unknown, n, 0, n, n, n],
						[1, i.Turbo, "Turbo", t.Unknown, n, 0, n, n, n],
						[1, i.Sleep, "Sleep", t.Unknown, n, 0, "VK_SLEEP", n, n],
						[1, i.WakeUp, "WakeUp", t.Unknown, n, 0, n, n, n],
						[0, i.KeyA, "KeyA", t.KeyA, "A", 65, "VK_A", n, n],
						[0, i.KeyB, "KeyB", t.KeyB, "B", 66, "VK_B", n, n],
						[0, i.KeyC, "KeyC", t.KeyC, "C", 67, "VK_C", n, n],
						[0, i.KeyD, "KeyD", t.KeyD, "D", 68, "VK_D", n, n],
						[0, i.KeyE, "KeyE", t.KeyE, "E", 69, "VK_E", n, n],
						[0, i.KeyF, "KeyF", t.KeyF, "F", 70, "VK_F", n, n],
						[0, i.KeyG, "KeyG", t.KeyG, "G", 71, "VK_G", n, n],
						[0, i.KeyH, "KeyH", t.KeyH, "H", 72, "VK_H", n, n],
						[0, i.KeyI, "KeyI", t.KeyI, "I", 73, "VK_I", n, n],
						[0, i.KeyJ, "KeyJ", t.KeyJ, "J", 74, "VK_J", n, n],
						[0, i.KeyK, "KeyK", t.KeyK, "K", 75, "VK_K", n, n],
						[0, i.KeyL, "KeyL", t.KeyL, "L", 76, "VK_L", n, n],
						[0, i.KeyM, "KeyM", t.KeyM, "M", 77, "VK_M", n, n],
						[0, i.KeyN, "KeyN", t.KeyN, "N", 78, "VK_N", n, n],
						[0, i.KeyO, "KeyO", t.KeyO, "O", 79, "VK_O", n, n],
						[0, i.KeyP, "KeyP", t.KeyP, "P", 80, "VK_P", n, n],
						[0, i.KeyQ, "KeyQ", t.KeyQ, "Q", 81, "VK_Q", n, n],
						[0, i.KeyR, "KeyR", t.KeyR, "R", 82, "VK_R", n, n],
						[0, i.KeyS, "KeyS", t.KeyS, "S", 83, "VK_S", n, n],
						[0, i.KeyT, "KeyT", t.KeyT, "T", 84, "VK_T", n, n],
						[0, i.KeyU, "KeyU", t.KeyU, "U", 85, "VK_U", n, n],
						[0, i.KeyV, "KeyV", t.KeyV, "V", 86, "VK_V", n, n],
						[0, i.KeyW, "KeyW", t.KeyW, "W", 87, "VK_W", n, n],
						[0, i.KeyX, "KeyX", t.KeyX, "X", 88, "VK_X", n, n],
						[0, i.KeyY, "KeyY", t.KeyY, "Y", 89, "VK_Y", n, n],
						[0, i.KeyZ, "KeyZ", t.KeyZ, "Z", 90, "VK_Z", n, n],
						[0, i.Digit1, "Digit1", t.Digit1, "1", 49, "VK_1", n, n],
						[0, i.Digit2, "Digit2", t.Digit2, "2", 50, "VK_2", n, n],
						[0, i.Digit3, "Digit3", t.Digit3, "3", 51, "VK_3", n, n],
						[0, i.Digit4, "Digit4", t.Digit4, "4", 52, "VK_4", n, n],
						[0, i.Digit5, "Digit5", t.Digit5, "5", 53, "VK_5", n, n],
						[0, i.Digit6, "Digit6", t.Digit6, "6", 54, "VK_6", n, n],
						[0, i.Digit7, "Digit7", t.Digit7, "7", 55, "VK_7", n, n],
						[0, i.Digit8, "Digit8", t.Digit8, "8", 56, "VK_8", n, n],
						[0, i.Digit9, "Digit9", t.Digit9, "9", 57, "VK_9", n, n],
						[0, i.Digit0, "Digit0", t.Digit0, "0", 48, "VK_0", n, n],
						[1, i.Enter, "Enter", t.Enter, "Enter", 13, "VK_RETURN", n, n],
						[1, i.Escape, "Escape", t.Escape, "Escape", 27, "VK_ESCAPE", n, n],
						[
							1,
							i.Backspace,
							"Backspace",
							t.Backspace,
							"Backspace",
							8,
							"VK_BACK",
							n,
							n,
						],
						[1, i.Tab, "Tab", t.Tab, "Tab", 9, "VK_TAB", n, n],
						[1, i.Space, "Space", t.Space, "Space", 32, "VK_SPACE", n, n],
						[
							0,
							i.Minus,
							"Minus",
							t.Minus,
							"-",
							189,
							"VK_OEM_MINUS",
							"-",
							"OEM_MINUS",
						],
						[
							0,
							i.Equal,
							"Equal",
							t.Equal,
							"=",
							187,
							"VK_OEM_PLUS",
							"=",
							"OEM_PLUS",
						],
						[
							0,
							i.BracketLeft,
							"BracketLeft",
							t.BracketLeft,
							"[",
							219,
							"VK_OEM_4",
							"[",
							"OEM_4",
						],
						[
							0,
							i.BracketRight,
							"BracketRight",
							t.BracketRight,
							"]",
							221,
							"VK_OEM_6",
							"]",
							"OEM_6",
						],
						[
							0,
							i.Backslash,
							"Backslash",
							t.Backslash,
							"\\",
							220,
							"VK_OEM_5",
							"\\",
							"OEM_5",
						],
						[0, i.IntlHash, "IntlHash", t.Unknown, n, 0, n, n, n],
						[
							0,
							i.Semicolon,
							"Semicolon",
							t.Semicolon,
							";",
							186,
							"VK_OEM_1",
							";",
							"OEM_1",
						],
						[0, i.Quote, "Quote", t.Quote, "'", 222, "VK_OEM_7", "'", "OEM_7"],
						[
							0,
							i.Backquote,
							"Backquote",
							t.Backquote,
							"`",
							192,
							"VK_OEM_3",
							"`",
							"OEM_3",
						],
						[
							0,
							i.Comma,
							"Comma",
							t.Comma,
							",",
							188,
							"VK_OEM_COMMA",
							",",
							"OEM_COMMA",
						],
						[
							0,
							i.Period,
							"Period",
							t.Period,
							".",
							190,
							"VK_OEM_PERIOD",
							".",
							"OEM_PERIOD",
						],
						[0, i.Slash, "Slash", t.Slash, "/", 191, "VK_OEM_2", "/", "OEM_2"],
						[
							1,
							i.CapsLock,
							"CapsLock",
							t.CapsLock,
							"CapsLock",
							20,
							"VK_CAPITAL",
							n,
							n,
						],
						[1, i.F1, "F1", t.F1, "F1", 112, "VK_F1", n, n],
						[1, i.F2, "F2", t.F2, "F2", 113, "VK_F2", n, n],
						[1, i.F3, "F3", t.F3, "F3", 114, "VK_F3", n, n],
						[1, i.F4, "F4", t.F4, "F4", 115, "VK_F4", n, n],
						[1, i.F5, "F5", t.F5, "F5", 116, "VK_F5", n, n],
						[1, i.F6, "F6", t.F6, "F6", 117, "VK_F6", n, n],
						[1, i.F7, "F7", t.F7, "F7", 118, "VK_F7", n, n],
						[1, i.F8, "F8", t.F8, "F8", 119, "VK_F8", n, n],
						[1, i.F9, "F9", t.F9, "F9", 120, "VK_F9", n, n],
						[1, i.F10, "F10", t.F10, "F10", 121, "VK_F10", n, n],
						[1, i.F11, "F11", t.F11, "F11", 122, "VK_F11", n, n],
						[1, i.F12, "F12", t.F12, "F12", 123, "VK_F12", n, n],
						[1, i.PrintScreen, "PrintScreen", t.Unknown, n, 0, n, n, n],
						[
							1,
							i.ScrollLock,
							"ScrollLock",
							t.ScrollLock,
							"ScrollLock",
							145,
							"VK_SCROLL",
							n,
							n,
						],
						[
							1,
							i.Pause,
							"Pause",
							t.PauseBreak,
							"PauseBreak",
							19,
							"VK_PAUSE",
							n,
							n,
						],
						[1, i.Insert, "Insert", t.Insert, "Insert", 45, "VK_INSERT", n, n],
						[1, i.Home, "Home", t.Home, "Home", 36, "VK_HOME", n, n],
						[1, i.PageUp, "PageUp", t.PageUp, "PageUp", 33, "VK_PRIOR", n, n],
						[1, i.Delete, "Delete", t.Delete, "Delete", 46, "VK_DELETE", n, n],
						[1, i.End, "End", t.End, "End", 35, "VK_END", n, n],
						[
							1,
							i.PageDown,
							"PageDown",
							t.PageDown,
							"PageDown",
							34,
							"VK_NEXT",
							n,
							n,
						],
						[
							1,
							i.ArrowRight,
							"ArrowRight",
							t.RightArrow,
							"RightArrow",
							39,
							"VK_RIGHT",
							"Right",
							n,
						],
						[
							1,
							i.ArrowLeft,
							"ArrowLeft",
							t.LeftArrow,
							"LeftArrow",
							37,
							"VK_LEFT",
							"Left",
							n,
						],
						[
							1,
							i.ArrowDown,
							"ArrowDown",
							t.DownArrow,
							"DownArrow",
							40,
							"VK_DOWN",
							"Down",
							n,
						],
						[
							1,
							i.ArrowUp,
							"ArrowUp",
							t.UpArrow,
							"UpArrow",
							38,
							"VK_UP",
							"Up",
							n,
						],
						[
							1,
							i.NumLock,
							"NumLock",
							t.NumLock,
							"NumLock",
							144,
							"VK_NUMLOCK",
							n,
							n,
						],
						[
							1,
							i.NumpadDivide,
							"NumpadDivide",
							t.NumpadDivide,
							"NumPad_Divide",
							111,
							"VK_DIVIDE",
							n,
							n,
						],
						[
							1,
							i.NumpadMultiply,
							"NumpadMultiply",
							t.NumpadMultiply,
							"NumPad_Multiply",
							106,
							"VK_MULTIPLY",
							n,
							n,
						],
						[
							1,
							i.NumpadSubtract,
							"NumpadSubtract",
							t.NumpadSubtract,
							"NumPad_Subtract",
							109,
							"VK_SUBTRACT",
							n,
							n,
						],
						[
							1,
							i.NumpadAdd,
							"NumpadAdd",
							t.NumpadAdd,
							"NumPad_Add",
							107,
							"VK_ADD",
							n,
							n,
						],
						[1, i.NumpadEnter, "NumpadEnter", t.Enter, n, 0, n, n, n],
						[
							1,
							i.Numpad1,
							"Numpad1",
							t.Numpad1,
							"NumPad1",
							97,
							"VK_NUMPAD1",
							n,
							n,
						],
						[
							1,
							i.Numpad2,
							"Numpad2",
							t.Numpad2,
							"NumPad2",
							98,
							"VK_NUMPAD2",
							n,
							n,
						],
						[
							1,
							i.Numpad3,
							"Numpad3",
							t.Numpad3,
							"NumPad3",
							99,
							"VK_NUMPAD3",
							n,
							n,
						],
						[
							1,
							i.Numpad4,
							"Numpad4",
							t.Numpad4,
							"NumPad4",
							100,
							"VK_NUMPAD4",
							n,
							n,
						],
						[
							1,
							i.Numpad5,
							"Numpad5",
							t.Numpad5,
							"NumPad5",
							101,
							"VK_NUMPAD5",
							n,
							n,
						],
						[
							1,
							i.Numpad6,
							"Numpad6",
							t.Numpad6,
							"NumPad6",
							102,
							"VK_NUMPAD6",
							n,
							n,
						],
						[
							1,
							i.Numpad7,
							"Numpad7",
							t.Numpad7,
							"NumPad7",
							103,
							"VK_NUMPAD7",
							n,
							n,
						],
						[
							1,
							i.Numpad8,
							"Numpad8",
							t.Numpad8,
							"NumPad8",
							104,
							"VK_NUMPAD8",
							n,
							n,
						],
						[
							1,
							i.Numpad9,
							"Numpad9",
							t.Numpad9,
							"NumPad9",
							105,
							"VK_NUMPAD9",
							n,
							n,
						],
						[
							1,
							i.Numpad0,
							"Numpad0",
							t.Numpad0,
							"NumPad0",
							96,
							"VK_NUMPAD0",
							n,
							n,
						],
						[
							1,
							i.NumpadDecimal,
							"NumpadDecimal",
							t.NumpadDecimal,
							"NumPad_Decimal",
							110,
							"VK_DECIMAL",
							n,
							n,
						],
						[
							0,
							i.IntlBackslash,
							"IntlBackslash",
							t.IntlBackslash,
							"OEM_102",
							226,
							"VK_OEM_102",
							n,
							n,
						],
						[
							1,
							i.ContextMenu,
							"ContextMenu",
							t.ContextMenu,
							"ContextMenu",
							93,
							n,
							n,
							n,
						],
						[1, i.Power, "Power", t.Unknown, n, 0, n, n, n],
						[1, i.NumpadEqual, "NumpadEqual", t.Unknown, n, 0, n, n, n],
						[1, i.F13, "F13", t.F13, "F13", 124, "VK_F13", n, n],
						[1, i.F14, "F14", t.F14, "F14", 125, "VK_F14", n, n],
						[1, i.F15, "F15", t.F15, "F15", 126, "VK_F15", n, n],
						[1, i.F16, "F16", t.F16, "F16", 127, "VK_F16", n, n],
						[1, i.F17, "F17", t.F17, "F17", 128, "VK_F17", n, n],
						[1, i.F18, "F18", t.F18, "F18", 129, "VK_F18", n, n],
						[1, i.F19, "F19", t.F19, "F19", 130, "VK_F19", n, n],
						[1, i.F20, "F20", t.F20, "F20", 131, "VK_F20", n, n],
						[1, i.F21, "F21", t.F21, "F21", 132, "VK_F21", n, n],
						[1, i.F22, "F22", t.F22, "F22", 133, "VK_F22", n, n],
						[1, i.F23, "F23", t.F23, "F23", 134, "VK_F23", n, n],
						[1, i.F24, "F24", t.F24, "F24", 135, "VK_F24", n, n],
						[1, i.Open, "Open", t.Unknown, n, 0, n, n, n],
						[1, i.Help, "Help", t.Unknown, n, 0, n, n, n],
						[1, i.Select, "Select", t.Unknown, n, 0, n, n, n],
						[1, i.Again, "Again", t.Unknown, n, 0, n, n, n],
						[1, i.Undo, "Undo", t.Unknown, n, 0, n, n, n],
						[1, i.Cut, "Cut", t.Unknown, n, 0, n, n, n],
						[1, i.Copy, "Copy", t.Unknown, n, 0, n, n, n],
						[1, i.Paste, "Paste", t.Unknown, n, 0, n, n, n],
						[1, i.Find, "Find", t.Unknown, n, 0, n, n, n],
						[
							1,
							i.AudioVolumeMute,
							"AudioVolumeMute",
							t.AudioVolumeMute,
							"AudioVolumeMute",
							173,
							"VK_VOLUME_MUTE",
							n,
							n,
						],
						[
							1,
							i.AudioVolumeUp,
							"AudioVolumeUp",
							t.AudioVolumeUp,
							"AudioVolumeUp",
							175,
							"VK_VOLUME_UP",
							n,
							n,
						],
						[
							1,
							i.AudioVolumeDown,
							"AudioVolumeDown",
							t.AudioVolumeDown,
							"AudioVolumeDown",
							174,
							"VK_VOLUME_DOWN",
							n,
							n,
						],
						[
							1,
							i.NumpadComma,
							"NumpadComma",
							t.NUMPAD_SEPARATOR,
							"NumPad_Separator",
							108,
							"VK_SEPARATOR",
							n,
							n,
						],
						[
							0,
							i.IntlRo,
							"IntlRo",
							t.ABNT_C1,
							"ABNT_C1",
							193,
							"VK_ABNT_C1",
							n,
							n,
						],
						[1, i.KanaMode, "KanaMode", t.Unknown, n, 0, n, n, n],
						[0, i.IntlYen, "IntlYen", t.Unknown, n, 0, n, n, n],
						[1, i.Convert, "Convert", t.Unknown, n, 0, n, n, n],
						[1, i.NonConvert, "NonConvert", t.Unknown, n, 0, n, n, n],
						[1, i.Lang1, "Lang1", t.Unknown, n, 0, n, n, n],
						[1, i.Lang2, "Lang2", t.Unknown, n, 0, n, n, n],
						[1, i.Lang3, "Lang3", t.Unknown, n, 0, n, n, n],
						[1, i.Lang4, "Lang4", t.Unknown, n, 0, n, n, n],
						[1, i.Lang5, "Lang5", t.Unknown, n, 0, n, n, n],
						[1, i.Abort, "Abort", t.Unknown, n, 0, n, n, n],
						[1, i.Props, "Props", t.Unknown, n, 0, n, n, n],
						[1, i.NumpadParenLeft, "NumpadParenLeft", t.Unknown, n, 0, n, n, n],
						[
							1,
							i.NumpadParenRight,
							"NumpadParenRight",
							t.Unknown,
							n,
							0,
							n,
							n,
							n,
						],
						[1, i.NumpadBackspace, "NumpadBackspace", t.Unknown, n, 0, n, n, n],
						[
							1,
							i.NumpadMemoryStore,
							"NumpadMemoryStore",
							t.Unknown,
							n,
							0,
							n,
							n,
							n,
						],
						[
							1,
							i.NumpadMemoryRecall,
							"NumpadMemoryRecall",
							t.Unknown,
							n,
							0,
							n,
							n,
							n,
						],
						[
							1,
							i.NumpadMemoryClear,
							"NumpadMemoryClear",
							t.Unknown,
							n,
							0,
							n,
							n,
							n,
						],
						[1, i.NumpadMemoryAdd, "NumpadMemoryAdd", t.Unknown, n, 0, n, n, n],
						[
							1,
							i.NumpadMemorySubtract,
							"NumpadMemorySubtract",
							t.Unknown,
							n,
							0,
							n,
							n,
							n,
						],
						[
							1,
							i.NumpadClear,
							"NumpadClear",
							t.Clear,
							"Clear",
							12,
							"VK_CLEAR",
							n,
							n,
						],
						[
							1,
							i.NumpadClearEntry,
							"NumpadClearEntry",
							t.Unknown,
							n,
							0,
							n,
							n,
							n,
						],
						[1, i.None, n, t.Ctrl, "Ctrl", 17, "VK_CONTROL", n, n],
						[1, i.None, n, t.Shift, "Shift", 16, "VK_SHIFT", n, n],
						[1, i.None, n, t.Alt, "Alt", 18, "VK_MENU", n, n],
						[1, i.None, n, t.Meta, "Meta", 91, "VK_COMMAND", n, n],
						[
							1,
							i.ControlLeft,
							"ControlLeft",
							t.Ctrl,
							n,
							0,
							"VK_LCONTROL",
							n,
							n,
						],
						[1, i.ShiftLeft, "ShiftLeft", t.Shift, n, 0, "VK_LSHIFT", n, n],
						[1, i.AltLeft, "AltLeft", t.Alt, n, 0, "VK_LMENU", n, n],
						[1, i.MetaLeft, "MetaLeft", t.Meta, n, 0, "VK_LWIN", n, n],
						[
							1,
							i.ControlRight,
							"ControlRight",
							t.Ctrl,
							n,
							0,
							"VK_RCONTROL",
							n,
							n,
						],
						[1, i.ShiftRight, "ShiftRight", t.Shift, n, 0, "VK_RSHIFT", n, n],
						[1, i.AltRight, "AltRight", t.Alt, n, 0, "VK_RMENU", n, n],
						[1, i.MetaRight, "MetaRight", t.Meta, n, 0, "VK_RWIN", n, n],
						[1, i.BrightnessUp, "BrightnessUp", t.Unknown, n, 0, n, n, n],
						[1, i.BrightnessDown, "BrightnessDown", t.Unknown, n, 0, n, n, n],
						[1, i.MediaPlay, "MediaPlay", t.Unknown, n, 0, n, n, n],
						[1, i.MediaRecord, "MediaRecord", t.Unknown, n, 0, n, n, n],
						[
							1,
							i.MediaFastForward,
							"MediaFastForward",
							t.Unknown,
							n,
							0,
							n,
							n,
							n,
						],
						[1, i.MediaRewind, "MediaRewind", t.Unknown, n, 0, n, n, n],
						[
							1,
							i.MediaTrackNext,
							"MediaTrackNext",
							t.MediaTrackNext,
							"MediaTrackNext",
							176,
							"VK_MEDIA_NEXT_TRACK",
							n,
							n,
						],
						[
							1,
							i.MediaTrackPrevious,
							"MediaTrackPrevious",
							t.MediaTrackPrevious,
							"MediaTrackPrevious",
							177,
							"VK_MEDIA_PREV_TRACK",
							n,
							n,
						],
						[
							1,
							i.MediaStop,
							"MediaStop",
							t.MediaStop,
							"MediaStop",
							178,
							"VK_MEDIA_STOP",
							n,
							n,
						],
						[1, i.Eject, "Eject", t.Unknown, n, 0, n, n, n],
						[
							1,
							i.MediaPlayPause,
							"MediaPlayPause",
							t.MediaPlayPause,
							"MediaPlayPause",
							179,
							"VK_MEDIA_PLAY_PAUSE",
							n,
							n,
						],
						[
							1,
							i.MediaSelect,
							"MediaSelect",
							t.LaunchMediaPlayer,
							"LaunchMediaPlayer",
							181,
							"VK_MEDIA_LAUNCH_MEDIA_SELECT",
							n,
							n,
						],
						[
							1,
							i.LaunchMail,
							"LaunchMail",
							t.LaunchMail,
							"LaunchMail",
							180,
							"VK_MEDIA_LAUNCH_MAIL",
							n,
							n,
						],
						[
							1,
							i.LaunchApp2,
							"LaunchApp2",
							t.LaunchApp2,
							"LaunchApp2",
							183,
							"VK_MEDIA_LAUNCH_APP2",
							n,
							n,
						],
						[
							1,
							i.LaunchApp1,
							"LaunchApp1",
							t.Unknown,
							n,
							0,
							"VK_MEDIA_LAUNCH_APP1",
							n,
							n,
						],
						[1, i.SelectTask, "SelectTask", t.Unknown, n, 0, n, n, n],
						[
							1,
							i.LaunchScreenSaver,
							"LaunchScreenSaver",
							t.Unknown,
							n,
							0,
							n,
							n,
							n,
						],
						[
							1,
							i.BrowserSearch,
							"BrowserSearch",
							t.BrowserSearch,
							"BrowserSearch",
							170,
							"VK_BROWSER_SEARCH",
							n,
							n,
						],
						[
							1,
							i.BrowserHome,
							"BrowserHome",
							t.BrowserHome,
							"BrowserHome",
							172,
							"VK_BROWSER_HOME",
							n,
							n,
						],
						[
							1,
							i.BrowserBack,
							"BrowserBack",
							t.BrowserBack,
							"BrowserBack",
							166,
							"VK_BROWSER_BACK",
							n,
							n,
						],
						[
							1,
							i.BrowserForward,
							"BrowserForward",
							t.BrowserForward,
							"BrowserForward",
							167,
							"VK_BROWSER_FORWARD",
							n,
							n,
						],
						[
							1,
							i.BrowserStop,
							"BrowserStop",
							t.Unknown,
							n,
							0,
							"VK_BROWSER_STOP",
							n,
							n,
						],
						[
							1,
							i.BrowserRefresh,
							"BrowserRefresh",
							t.Unknown,
							n,
							0,
							"VK_BROWSER_REFRESH",
							n,
							n,
						],
						[
							1,
							i.BrowserFavorites,
							"BrowserFavorites",
							t.Unknown,
							n,
							0,
							"VK_BROWSER_FAVORITES",
							n,
							n,
						],
						[1, i.ZoomToggle, "ZoomToggle", t.Unknown, n, 0, n, n, n],
						[1, i.MailReply, "MailReply", t.Unknown, n, 0, n, n, n],
						[1, i.MailForward, "MailForward", t.Unknown, n, 0, n, n, n],
						[1, i.MailSend, "MailSend", t.Unknown, n, 0, n, n, n],
						[
							1,
							i.None,
							n,
							t.KEY_IN_COMPOSITION,
							"KeyInComposition",
							229,
							n,
							n,
							n,
						],
						[1, i.None, n, t.ABNT_C2, "ABNT_C2", 194, "VK_ABNT_C2", n, n],
						[1, i.None, n, t.OEM_8, "OEM_8", 223, "VK_OEM_8", n, n],
						[1, i.None, n, t.Unknown, n, 0, "VK_KANA", n, n],
						[1, i.None, n, t.Unknown, n, 0, "VK_HANGUL", n, n],
						[1, i.None, n, t.Unknown, n, 0, "VK_JUNJA", n, n],
						[1, i.None, n, t.Unknown, n, 0, "VK_FINAL", n, n],
						[1, i.None, n, t.Unknown, n, 0, "VK_HANJA", n, n],
						[1, i.None, n, t.Unknown, n, 0, "VK_KANJI", n, n],
						[1, i.None, n, t.Unknown, n, 0, "VK_CONVERT", n, n],
						[1, i.None, n, t.Unknown, n, 0, "VK_NONCONVERT", n, n],
						[1, i.None, n, t.Unknown, n, 0, "VK_ACCEPT", n, n],
						[1, i.None, n, t.Unknown, n, 0, "VK_MODECHANGE", n, n],
						[1, i.None, n, t.Unknown, n, 0, "VK_SELECT", n, n],
						[1, i.None, n, t.Unknown, n, 0, "VK_PRINT", n, n],
						[1, i.None, n, t.Unknown, n, 0, "VK_EXECUTE", n, n],
						[1, i.None, n, t.Unknown, n, 0, "VK_SNAPSHOT", n, n],
						[1, i.None, n, t.Unknown, n, 0, "VK_HELP", n, n],
						[1, i.None, n, t.Unknown, n, 0, "VK_APPS", n, n],
						[1, i.None, n, t.Unknown, n, 0, "VK_PROCESSKEY", n, n],
						[1, i.None, n, t.Unknown, n, 0, "VK_PACKET", n, n],
						[1, i.None, n, t.Unknown, n, 0, "VK_DBE_SBCSCHAR", n, n],
						[1, i.None, n, t.Unknown, n, 0, "VK_DBE_DBCSCHAR", n, n],
						[1, i.None, n, t.Unknown, n, 0, "VK_ATTN", n, n],
						[1, i.None, n, t.Unknown, n, 0, "VK_CRSEL", n, n],
						[1, i.None, n, t.Unknown, n, 0, "VK_EXSEL", n, n],
						[1, i.None, n, t.Unknown, n, 0, "VK_EREOF", n, n],
						[1, i.None, n, t.Unknown, n, 0, "VK_PLAY", n, n],
						[1, i.None, n, t.Unknown, n, 0, "VK_ZOOM", n, n],
						[1, i.None, n, t.Unknown, n, 0, "VK_NONAME", n, n],
						[1, i.None, n, t.Unknown, n, 0, "VK_PA1", n, n],
						[1, i.None, n, t.Unknown, n, 0, "VK_OEM_CLEAR", n, n],
					],
					p = [],
					o = [];
				for (const f of g) {
					const [b, s, l, y, $, v, S, I, T] = f;
					if (
						(o[s] ||
							((o[s] = !0),
							(m[s] = l),
							(r[l] = s),
							(u[l.toLowerCase()] = s),
							b &&
								((e.$ms[s] = y),
								y !== t.Unknown &&
									y !== t.Enter &&
									y !== t.Ctrl &&
									y !== t.Shift &&
									y !== t.Alt &&
									y !== t.Meta &&
									(e.$ns[y] = s))),
						!p[y])
					) {
						if (((p[y] = !0), !$))
							throw new Error(
								`String representation missing for key code ${y} around scan code ${l}`,
							);
						E.define(y, $), C.define(y, I || $), d.define(y, T || I || $);
					}
					v && (e.$js[v] = y), S && (e.$ks[S] = y);
				}
				e.$ns[t.Enter] = i.Enter;
			})();
			var a;
			(function (n) {
				function g(l) {
					return E.keyCodeToStr(l);
				}
				n.toString = g;
				function p(l) {
					return E.strToKeyCode(l);
				}
				n.fromString = p;
				function o(l) {
					return C.keyCodeToStr(l);
				}
				n.toUserSettingsUS = o;
				function f(l) {
					return d.keyCodeToStr(l);
				}
				n.toUserSettingsGeneral = f;
				function b(l) {
					return C.strToKeyCode(l) || d.strToKeyCode(l);
				}
				n.fromUserSettings = b;
				function s(l) {
					if (l >= t.Numpad0 && l <= t.NumpadDivide) return null;
					switch (l) {
						case t.UpArrow:
							return "Up";
						case t.DownArrow:
							return "Down";
						case t.LeftArrow:
							return "Left";
						case t.RightArrow:
							return "Right";
					}
					return E.keyCodeToStr(l);
				}
				n.toElectronAccelerator = s;
			})(a || (e.KeyCodeUtils = a = {}));
			var h;
			(function (n) {
				(n[(n.CtrlCmd = 2048)] = "CtrlCmd"),
					(n[(n.Shift = 1024)] = "Shift"),
					(n[(n.Alt = 512)] = "Alt"),
					(n[(n.WinCtrl = 256)] = "WinCtrl");
			})(h || (e.KeyMod = h = {}));
			function c(n, g) {
				const p = ((g & 65535) << 16) >>> 0;
				return (n | p) >>> 0;
			}
			(e.$ps = h.CtrlCmd | t.KeyM), (e.$qs = h.CtrlCmd | t.KeyR);
		})
