import '../../../../../../require.js';
import '../../../../../../exports.js';
define(de[1253], he([1, 0]), function (ce, e) {
			"use strict";
			Object.defineProperty(e, "__esModule", { value: !0 }),
				(e.$xEc = e.$wEc = e.$vEc = e.$uEc = void 0),
				(e.$uEc = { top: 24, bottom: 24 }),
				(e.$vEc = { top: 12, bottom: 12 }),
				(e.$wEc = {
					padding: e.$vEc,
					scrollBeyondLastLine: !1,
					scrollbar: {
						verticalScrollbarSize: 14,
						horizontal: "auto",
						vertical: "auto",
						useShadows: !0,
						verticalHasArrows: !1,
						horizontalHasArrows: !1,
						alwaysConsumeMouseWheel: !1,
					},
					renderLineHighlightOnlyWhenFocus: !0,
					overviewRulerLanes: 0,
					overviewRulerBorder: !1,
					selectOnLineNumbers: !1,
					wordWrap: "off",
					lineNumbers: "off",
					glyphMargin: !0,
					fixedOverflowWidgets: !0,
					minimap: { enabled: !1 },
					renderValidationDecorations: "on",
					renderLineHighlight: "none",
					readOnly: !0,
				}),
				(e.$xEc = {
					...e.$wEc,
					glyphMargin: !0,
					enableSplitViewResizing: !1,
					renderIndicators: !0,
					renderMarginRevertIcon: !1,
					readOnly: !1,
					isInEmbeddedEditor: !0,
					renderOverviewRuler: !1,
					wordWrap: "off",
					diffWordWrap: "off",
					diffAlgorithm: "advanced",
					renderSideBySide: !0,
					useInlineViewWhenSpaceIsLimited: !1,
				});
		}),
		